<a href="https://colab.research.google.com/github/veeraswamy87/PythonExamples/blob/master/Python_Basic_Examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Concat Two Tuples

In [8]:
tup1 = ("Veeraswamy", 2 ,True)

In [6]:
tup2 = ("Gatta", 3 ,False)

In [9]:
tup1 + tup2

('Veeraswamy', 2, True, 'Gatta', 3, False)

NumPy

In [12]:
import numpy as np
n1=np.zeros((5,5))
print(n1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


What is Pandas 

It deals with large variety of data and its open source library

it provides two  fantastic data structures ( Series and DataFames)

Dataframes - its mutable data type present in pandas library and provides support for heterogeneous data

In [17]:
import pandas as pd

df = pd.read_csv("/content/sample_data/california_housing_test.csv")
df.head(2)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0   
1    -118.30     34.26                43.0       1510.0           310.0   

   population  households  median_income  median_house_value  
0      1537.0       606.0         6.6085            344700.0  
1       809.0       277.0         3.5990            176500.0

In [19]:
import pandas as pd

data = ["1", "two","3.5","4"]

series = pd.Series(data)
print(series)
print(type(series))

0      1
1    two
2    3.5
3      4
dtype: object
<class 'pandas.core.series.Series'>


In [23]:
import pandas as pd

df = pd.DataFrame({ "Name": ["veeraswamy","siva","sravan","nandhu"], "Age":[35,35,6,5]})

print(df)

df.groupby("Age").count()


         Name  Age
0  veeraswamy   35
1        siva   35
2      sravan    6
3      nandhu    5


Name
Age      
5       1
6       1
35      2

In [25]:
import pandas as pd

df =pd.DataFrame()

names = ['Veera','Siva','Sravan','Nandhu']

year = [1988,1988,2016,2018]

df['names']=names
df['year']=year

print(df)

    names  year
0   Veera  1988
1    Siva  1988
2  Sravan  2016
3  Nandhu  2018


In [26]:
import pandas as pd


names = ['Veera','Siva','Sravan','Nandhu']

year = [1988,1988,2016,2018]

d={'names':names,"year":year}

df =pd.DataFrame(d)

print(df)

    names  year
0   Veera  1988
1    Siva  1988
2  Sravan  2016
3  Nandhu  2018


Dictonary :   {}    {key:value,key:value}

List :  []   ["value","value"]

Tupe : ()   ("value",'value')

Pandas support left,right,inner and outer join and its horizontal stacking

For vertical stacking ,need to use contact method

In [27]:
# Single Line Comment

"""
Mutliple lines 

Comment

"""

print('Hello')

Hello


Tuples are immutable ,you cant add anthing to exist tuple

In [31]:
import numpy as np

array= [10,30,5,25,26]

n1=np.array([2,3,5,6])

print(np.median(array))
print(np.min(array))
print(np.max(array))
print(np.std(array))

print(np.min(n1))

25.0
5
30
9.826494797230596
2


In [37]:
str = 'veerSwamy Gatta'

print(str.lower())
print(str.upper())
print(str.capitalize())
print(str.split())

split =str.split()

for s in split:
  print(s.capitalize())

veerswamy gatta
VEERSWAMY GATTA
Veerswamy gatta
['veerSwamy', 'Gatta']
Veerswamy
Gatta


In [7]:
l = [1,2,3,4,5,6,8,9]
l.insert(6,7)
print(l)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [8]:

l = ['v','s','s','n']

unique=list(dict.fromkeys(l))
print(unique)

['v', 's', 'n']


Comprehension - tranforming one list to anther list

In [15]:
list = [i for i in range(1000)]
print(list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,

In [21]:
l = [1,2,3,4,5]

def multiply(n):
    return n * 2


m =map(multiply,l)

print(list(m))

[2, 4, 6, 8, 10]


In [43]:
class Cons:

   def __init__(self,name,age):
       self.name=name
       self.age=age
  
   def sayHello(self):
       print("Hello " , self.name + "  your age is ", self.age)

con = Cons("veeraswamy Gatta",20)
con.sayHello()
  

Hello  veeraswamy Gatta  your age is  20


In [44]:
v ="veeraswAMY,GATTA,sravan,kumar"
v1 = v.split(",")
print(v1)

['veeraswAMY', 'GATTA', 'sravan', 'kumar']


In [46]:
sum = lambda s: s+10

print(sum(10))

{20}


In [48]:
func = lambda a, b: (
    b - a if a <= b else
    a * b
)

print(func(2, 10))


8


In [49]:
sequences = [10,2,8,7,5,4,3,11,0, 1]
filtered_result = filter (lambda x: x > 4, sequences) 
print(list(filtered_result))

[10, 8, 7, 5, 11]


In [52]:
from functools import reduce
sequences = [1,2,3,4]
product = reduce (lambda x, y: x*y, sequences)
print(product)

24


In [53]:
class CSStudent:
    stream = 'cse'                  # Class Variable
    def __init__(self,name,roll):
        self.name = name            # Instance Variable
        self.roll = roll            # Instance Variable
 
# Objects of CSStudent class
a = CSStudent('Geek', 1)
b = CSStudent('Nerd', 2)
 
print(a.stream)  # prints "cse"
print(b.stream)  # prints "cse"
print(a.name)    # prints "Geek"
print(b.name)    # prints "Nerd"
print(a.roll)    # prints "1"
print(b.roll)    # prints "2"
 
# Class variables can be accessed using class
# name also
print(CSStudent.stream) # prints "cse"
 
# Now if we change the stream for just a it won't be changed for b
a.stream = 'ece'
print(a.stream) # prints 'ece'
print(b.stream) # prints 'cse'
 
# To change the stream for all instances of the class we can change it
# directly from the class
CSStudent.stream = 'mech'
 
print(a.stream) # prints 'ece'
print(b.stream) # prints 'mech'c

cse
cse
Geek
Nerd
1
2
cse
ece
cse
ece
mech


In [56]:
a = [1, 2, 3]
try:
    print ("Second element = %d" %(a[1]))
 
    # Throws error since there are only 3 elements in array
    print ("Fourth element = %d" %(a[3]))
 
except:
    print ("An error occurred")

Second element = 2
An error occurred


In [60]:
def fun(a):
    if a < 4:
 
        # throws ZeroDivisionError for a = 3
        b = a/(a-3)
 
    # throws NameError if a >= 4
    print("Value of b = ", b)
     
try:
    fun(2)
    fun(5)
 
# note that braces () are necessary here for
# multiple exceptions
except ZeroDivisionError:
    print("ZeroDivisionError Occurred and Handled")
except NameError:
    print("NameError Occurred and Handled")

Value of b =  -2.0
NameError Occurred and Handled


In [64]:
try:
    raise NameError("Hi there")  # Raise Error
except NameError:
    print ("An exception")
    raise  # To determine whether the exception was raised or not

An exception


In [66]:
# initialize the amount variable
amount = 10000
  
# check that You are eligible to
#  purchase Dsa Self Paced or not
if(amount>2999):
    print("You are eligible to purchase Dsa Self Paced")

You are eligible to purchase Dsa Self Paced


In [67]:
try:  
    a = 10/1  
    print (a)
except ArithmeticError:  
        print ("This statement is raising an arithmetic exception.")
else:  
    print ("Success.")

10.0
Success.


In [68]:
# class Error is derived from super class Exception
class Error(Exception):
 
    # Error is derived class for Exception, but
    # Base class for exceptions in this module
    pass
 
class TransitionError(Error):
 
    # Raised when an operation attempts a state
    # transition that's not allowed.
    def __init__(self, prev, nex, msg):
        self.prev = prev
        self.next = nex
 
        # Error message thrown is saved in msg
        self.msg = msg
try:
    raise(TransitionError(2,3*2,"Not Allowed"))
 
# Value of Exception is stored in error
except TransitionError as error:
    print('Exception occured: ',error.msg)

Exception occured:  Not Allowed


In [69]:
# Python code to illustrate with() alongwith write()
with open("file.txt", "w") as f:
    f.write("Hello World!!!")

In [73]:
# Python code to illustrate split() function
with open("file.txt", "r") as file:
	data = file.readlines()
	for line in data:
		word = line.split()
		print (word)



['Hello', 'World!!!']


In [74]:
# Python program to demonstrate
# opening a file


# Open function to open the file "myfile.txt"
# (same directory) in append mode and store
# it's reference in the variable file1
file1 = open("myfile.txt", "a")

# Writing to file
file1.write("\nWriting to file :)")

# Closing file
file1.close()


In [75]:
# Program to show various ways to
# read data from a file.

# Creating a file
file1 = open("myfile.txt", "w")
L = ["This is Delhi \n", "This is Paris \n", "This is London \n"]

# Writing data to a file
file1.write("Hello \n")
file1.writelines(L)
file1.close() # to change file access modes

file1 = open("myfile.txt", "r+")

print("Output of Read function is ")
print(file1.read())
print()

# seek(n) takes the file handle to the nth
# bite from the beginning.
file1.seek(0)

print("Output of Readline function is ")
print(file1.readline())
print()

file1.seek(0)

# To show difference between read and readline
print("Output of Read(9) function is ")
print(file1.read(9))
print()

file1.seek(0)

print("Output of Readline(9) function is ")
print(file1.readline(9))
print()

file1.seek(0)

# readlines function
print("Output of Readlines function is ")
print(file1.readlines())
print()
file1.close()


Output of Read function is 
Hello 
This is Delhi 
This is Paris 
This is London 


Output of Readline function is 
Hello 


Output of Read(9) function is 
Hello 
Th

Output of Readline(9) function is 
Hello 


Output of Readlines function is 
['Hello \n', 'This is Delhi \n', 'This is Paris \n', 'This is London \n']

