<a href="https://colab.research.google.com/github/veeraswamy87/PythonExamples/blob/master/Python_Basic_Examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Concat Two Tuples

In [8]:
tup1 = ("Veeraswamy", 2 ,True)

In [6]:
tup2 = ("Gatta", 3 ,False)

In [9]:
tup1 + tup2

('Veeraswamy', 2, True, 'Gatta', 3, False)

NumPy

In [12]:
import numpy as np
n1=np.zeros((5,5))
print(n1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


What is Pandas 

It deals with large variety of data and its open source library

it provides two  fantastic data structures ( Series and DataFames)

Dataframes - its mutable data type present in pandas library and provides support for heterogeneous data

In [ ]:
import pandas as pd

df = pd.read_csv("/content/sample_data/california_housing_test.csv")
df.head(2)

In [19]:
import pandas as pd

data = ["1", "two","3.5","4"]

series = pd.Series(data)
print(series)
print(type(series))

0      1
1    two
2    3.5
3      4
dtype: object
<class 'pandas.core.series.Series'>


In [23]:
import pandas as pd

df = pd.DataFrame({ "Name": ["veeraswamy","siva","sravan","nandhu"], "Age":[35,35,6,5]})

print(df)

df.groupby("Age").count()


         Name  Age
0  veeraswamy   35
1        siva   35
2      sravan    6
3      nandhu    5


Name
Age      
5       1
6       1
35      2

In [25]:
import pandas as pd

df =pd.DataFrame()

names = ['Veera','Siva','Sravan','Nandhu']

year = [1988,1988,2016,2018]

df['names']=names
df['year']=year

print(df)

    names  year
0   Veera  1988
1    Siva  1988
2  Sravan  2016
3  Nandhu  2018


In [26]:
import pandas as pd


names = ['Veera','Siva','Sravan','Nandhu']

year = [1988,1988,2016,2018]

d={'names':names,"year":year}

df =pd.DataFrame(d)

print(df)

    names  year
0   Veera  1988
1    Siva  1988
2  Sravan  2016
3  Nandhu  2018


Dictonary :   {}    {key:value,key:value}

List :  []   ["value","value"]

Tupe : ()   ("value",'value')

Pandas support left,right,inner and outer join and its horizontal stacking

For vertical stacking ,need to use contact method

In [27]:
# Single Line Comment

"""
Mutliple lines 

Comment

"""

print('Hello')

Hello


Tuples are immutable ,you cant add anthing to exist tuple

In [31]:
import numpy as np

array= [10,30,5,25,26]

n1=np.array([2,3,5,6])

print(np.median(array))
print(np.min(array))
print(np.max(array))
print(np.std(array))

print(np.min(n1))

25.0
5
30
9.826494797230596
2


In [37]:
str = 'veerSwamy Gatta'

print(str.lower())
print(str.upper())
print(str.capitalize())
print(str.split())

split =str.split()

for s in split:
  print(s.capitalize())

veerswamy gatta
VEERSWAMY GATTA
Veerswamy gatta
['veerSwamy', 'Gatta']
Veerswamy
Gatta


In [7]:
l = [1,2,3,4,5,6,8,9]
l.insert(6,7)
print(l)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [8]:

l = ['v','s','s','n']

unique=list(dict.fromkeys(l))
print(unique)

['v', 's', 'n']


Comprehension - tranforming one list to anther list

In [ ]:
list = [i for i in range(1000)]
print(list)

In [21]:
l = [1,2,3,4,5]

def multiply(n):
    return n * 2


m =map(multiply,l)

print(list(m))

[2, 4, 6, 8, 10]


In [43]:
class Cons:

   def __init__(self,name,age):
       self.name=name
       self.age=age
  
   def sayHello(self):
       print("Hello " , self.name + "  your age is ", self.age)

con = Cons("veeraswamy Gatta",20)
con.sayHello()
  

Hello  veeraswamy Gatta  your age is  20


In [44]:
v ="veeraswAMY,GATTA,sravan,kumar"
v1 = v.split(",")
print(v1)

['veeraswAMY', 'GATTA', 'sravan', 'kumar']


In [46]:
sum = lambda s: s+10

print(sum(10))

{20}


In [48]:
func = lambda a, b: (
    b - a if a <= b else
    a * b
)

print(func(2, 10))


8


In [49]:
sequences = [10,2,8,7,5,4,3,11,0, 1]
filtered_result = filter (lambda x: x > 4, sequences) 
print(list(filtered_result))

[10, 8, 7, 5, 11]


In [52]:
from functools import reduce
sequences = [1,2,3,4]
product = reduce (lambda x, y: x*y, sequences)
print(product)

24


In [53]:
class CSStudent:
    stream = 'cse'                  # Class Variable
    def __init__(self,name,roll):
        self.name = name            # Instance Variable
        self.roll = roll            # Instance Variable
 
# Objects of CSStudent class
a = CSStudent('Geek', 1)
b = CSStudent('Nerd', 2)
 
print(a.stream)  # prints "cse"
print(b.stream)  # prints "cse"
print(a.name)    # prints "Geek"
print(b.name)    # prints "Nerd"
print(a.roll)    # prints "1"
print(b.roll)    # prints "2"
 
# Class variables can be accessed using class
# name also
print(CSStudent.stream) # prints "cse"
 
# Now if we change the stream for just a it won't be changed for b
a.stream = 'ece'
print(a.stream) # prints 'ece'
print(b.stream) # prints 'cse'
 
# To change the stream for all instances of the class we can change it
# directly from the class
CSStudent.stream = 'mech'
 
print(a.stream) # prints 'ece'
print(b.stream) # prints 'mech'c

cse
cse
Geek
Nerd
1
2
cse
ece
cse
ece
mech


In [56]:
a = [1, 2, 3]
try:
    print ("Second element = %d" %(a[1]))
 
    # Throws error since there are only 3 elements in array
    print ("Fourth element = %d" %(a[3]))
 
except:
    print ("An error occurred")

Second element = 2
An error occurred


In [60]:
def fun(a):
    if a < 4:
 
        # throws ZeroDivisionError for a = 3
        b = a/(a-3)
 
    # throws NameError if a >= 4
    print("Value of b = ", b)
     
try:
    fun(2)
    fun(5)
 
# note that braces () are necessary here for
# multiple exceptions
except ZeroDivisionError:
    print("ZeroDivisionError Occurred and Handled")
except NameError:
    print("NameError Occurred and Handled")

Value of b =  -2.0
NameError Occurred and Handled


In [64]:
try:
    raise NameError("Hi there")  # Raise Error
except NameError:
    print ("An exception")
    raise  # To determine whether the exception was raised or not

An exception


In [66]:
# initialize the amount variable
amount = 10000
  
# check that You are eligible to
#  purchase Dsa Self Paced or not
if(amount>2999):
    print("You are eligible to purchase Dsa Self Paced")

You are eligible to purchase Dsa Self Paced


In [67]:
try:  
    a = 10/1  
    print (a)
except ArithmeticError:  
        print ("This statement is raising an arithmetic exception.")
else:  
    print ("Success.")

10.0
Success.


In [68]:
# class Error is derived from super class Exception
class Error(Exception):
 
    # Error is derived class for Exception, but
    # Base class for exceptions in this module
    pass
 
class TransitionError(Error):
 
    # Raised when an operation attempts a state
    # transition that's not allowed.
    def __init__(self, prev, nex, msg):
        self.prev = prev
        self.next = nex
 
        # Error message thrown is saved in msg
        self.msg = msg
try:
    raise(TransitionError(2,3*2,"Not Allowed"))
 
# Value of Exception is stored in error
except TransitionError as error:
    print('Exception occured: ',error.msg)

Exception occured:  Not Allowed


In [69]:
# Python code to illustrate with() alongwith write()
with open("file.txt", "w") as f:
    f.write("Hello World!!!")

In [73]:
# Python code to illustrate split() function
with open("file.txt", "r") as file:
	data = file.readlines()
	for line in data:
		word = line.split()
		print (word)



['Hello', 'World!!!']


In [74]:
# Python program to demonstrate
# opening a file


# Open function to open the file "myfile.txt"
# (same directory) in append mode and store
# it's reference in the variable file1
file1 = open("myfile.txt", "a")

# Writing to file
file1.write("\nWriting to file :)")

# Closing file
file1.close()


In [75]:
# Program to show various ways to
# read data from a file.

# Creating a file
file1 = open("myfile.txt", "w")
L = ["This is Delhi \n", "This is Paris \n", "This is London \n"]

# Writing data to a file
file1.write("Hello \n")
file1.writelines(L)
file1.close() # to change file access modes

file1 = open("myfile.txt", "r+")

print("Output of Read function is ")
print(file1.read())
print()

# seek(n) takes the file handle to the nth
# bite from the beginning.
file1.seek(0)

print("Output of Readline function is ")
print(file1.readline())
print()

file1.seek(0)

# To show difference between read and readline
print("Output of Read(9) function is ")
print(file1.read(9))
print()

file1.seek(0)

print("Output of Readline(9) function is ")
print(file1.readline(9))
print()

file1.seek(0)

# readlines function
print("Output of Readlines function is ")
print(file1.readlines())
print()
file1.close()


Output of Read function is 
Hello 
This is Delhi 
This is Paris 
This is London 


Output of Readline function is 
Hello 


Output of Read(9) function is 
Hello 
Th

Output of Readline(9) function is 
Hello 


Output of Readlines function is 
['Hello \n', 'This is Delhi \n', 'This is Paris \n', 'This is London \n']



In [77]:
# Python program to illustrate
# Append vs write mode
with open("myfile.txt", "w") as file1 :
       L = ["This is Delhi \n", "This is Paris \n", "This is London \n"]
       file1.writelines(L)

# Append-adds at last
file1 = open("myfile.txt", "a") # append mode
file1.write("Today \n")
file1.close()

file1 = open("myfile.txt", "r")
print("Output of Readlines after appending")
print(file1.read())
print()
file1.close()

# Write-Overwrites
file1 = open("myfile.txt", "w") # write mode
file1.write("Tomorrow \n")
file1.close()

file1 = open("myfile.txt", "r")
print("Output of Readlines after writing")
print(file1.read())
print()
file1.close()


Output of Readlines after appending
This is Delhi 
This is Paris 
This is London 
Today 


Output of Readlines after writing
Tomorrow 




In [ ]:
# importing required library
from pip._internal import main
main(['install','mysql-connector-python-rf'])

import mysql.connector

# connecting to the database
dataBase = mysql.connector.connect(
					host = "localhost",
					user = "user",
					passwd = "gfg",
					database = "geeks4geeks" )

# preparing a cursor object
cursorObject = dataBase.cursor()

# creating table
studentRecord = """CREATE TABLE STUDENT (
				NAME VARCHAR(20) NOT NULL,
				BRANCH VARCHAR(50),
				ROLL INT NOT NULL,
				SECTION VARCHAR(5),
				AGE INT
				)"""

# table created
cursorObject.execute(studentRecord)

# disconnecting from server
dataBase.close()


In [84]:
!pip install mysql-connector-python-rf

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [87]:
# Python program to illustrate the concept
# of threading
# importing the threading module
import threading

def print_cube(num):
	"""
	function to print cube of given num
	"""
	print("Cube: {}".format(num * num * num))

def print_square(num):
	"""
	function to print square of given num
	"""
	print("Square: {}".format(num * num))

if __name__ == "__main__":
	# creating thread
	t1 = threading.Thread(target=print_square, args=(10,))
	t2 = threading.Thread(target=print_cube, args=(10,))

	# starting thread 1
	t1.start()
	# starting thread 2
	t2.start()

	# wait until thread 1 is completely executed
	t1.join()
	# wait until thread 2 is completely executed
	t2.join()

	# both threads completely executed
	print("Done!")


Square: 100Cube: 1000

Done!


In [89]:
import json
var = {
	"Subjects": {
				"Maths":85,
				"Physics":90
				}
	}

with open("Sample.json", "w") as p:
	json.dump(var, p)


In [90]:
with open("Sample.json", "r") as read_it:
	data = json.load(read_it)


In [91]:
json_var ="""
{
	"Country": {
		"name": "INDIA",
		"Languages_spoken": [
			{
				"names": ["Hindi", "English", "Bengali", "Telugu"]
			}
		]
	}
}
"""
var = json.loads(json_var)


In [4]:
# Python program to illustrate
# closures
def outerFunction(text):
	text = text

	def innerFunction():
		print(text)

	# Note we are returning function
	# WITHOUT parenthesis
	return innerFunction

if __name__ == '__main__':
	myFunction = outerFunction('Hey!')
myFunction()


Hey!


In [7]:
# Python code
# To reverse words in a given string

# input string
string = "Veeraswamy Gatta"
# reversing words in a given string
s = string.split()[::-1]
l = []
for i in s:
	# apending reversed words to l
	l.append(i)
# printing reverse words
print(" ".join(l))


Gatta Veeraswamy


In [8]:
# Python3 program to find whether the string
# has all same characters or not.

# Function to check the string has
# all same characters or not .
def allCharactersSame(s) :
	n = len(s)
	for i in range(1, n) :
		if s[i] != s[0] :
			return False

	return True

# Driver code
if __name__ == "__main__" :
	
	s = "aaa"
	if allCharactersSame(s) :
		print("Yes")
	else :
		print("No")

# This code is contributed by ANKITRAI1


Yes


In [ ]:
!pip list

In [5]:
import requests
import time

img_urls = [
    'https://images.unsplash.com/photo-1516117172878-fd2c41f4a759',
    'https://images.unsplash.com/photo-1532009324734-20a7a5813719',
    'https://images.unsplash.com/photo-1524429656589-6633a470097c',
    'https://images.unsplash.com/photo-1530224264768-7ff8c1789d79',
    'https://images.unsplash.com/photo-1564135624576-c5c88640f235',
    'https://images.unsplash.com/photo-1541698444083-023c97d3f4b6',
    'https://images.unsplash.com/photo-1522364723953-452d3431c267',
    'https://images.unsplash.com/photo-1513938709626-033611b8cc03',
    'https://images.unsplash.com/photo-1507143550189-fed454f93097',
    'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e',
    'https://images.unsplash.com/photo-1504198453319-5ce911bafcde',
    'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99',
    'https://images.unsplash.com/photo-1516972810927-80185027ca84',
    'https://images.unsplash.com/photo-1550439062-609e1531270e',
    'https://images.unsplash.com/photo-1549692520-acc6669e2f0c'
]

t1 = time.perf_counter()


for img_url in img_urls:
    img_bytes = requests.get(img_url).content
    img_name = img_url.split('/')[3]
    img_name = f'{img_name}.jpg'
    with open(img_name, 'wb') as img_file:
        img_file.write(img_bytes)
        print(f'{img_name} was downloaded...')

t2 = time.perf_counter()

print(f'Finished in {t2-t1} seconds')

photo-1516117172878-fd2c41f4a759.jpg was downloaded...
photo-1532009324734-20a7a5813719.jpg was downloaded...
photo-1524429656589-6633a470097c.jpg was downloaded...
photo-1530224264768-7ff8c1789d79.jpg was downloaded...
photo-1564135624576-c5c88640f235.jpg was downloaded...
photo-1541698444083-023c97d3f4b6.jpg was downloaded...
photo-1522364723953-452d3431c267.jpg was downloaded...
photo-1513938709626-033611b8cc03.jpg was downloaded...
photo-1507143550189-fed454f93097.jpg was downloaded...
photo-1493976040374-85c8e12f0c0e.jpg was downloaded...
photo-1504198453319-5ce911bafcde.jpg was downloaded...
photo-1530122037265-a5f1f91d3b99.jpg was downloaded...
photo-1516972810927-80185027ca84.jpg was downloaded...
photo-1550439062-609e1531270e.jpg was downloaded...
photo-1549692520-acc6669e2f0c.jpg was downloaded...
Finished in 2.065649735999955 seconds


In [1]:
import requests
import time
import concurrent.futures

img_urls = [
    'https://images.unsplash.com/photo-1516117172878-fd2c41f4a759',
    'https://images.unsplash.com/photo-1532009324734-20a7a5813719',
    'https://images.unsplash.com/photo-1524429656589-6633a470097c',
    'https://images.unsplash.com/photo-1530224264768-7ff8c1789d79',
    'https://images.unsplash.com/photo-1564135624576-c5c88640f235',
    'https://images.unsplash.com/photo-1541698444083-023c97d3f4b6',
    'https://images.unsplash.com/photo-1522364723953-452d3431c267',
    'https://images.unsplash.com/photo-1513938709626-033611b8cc03',
    'https://images.unsplash.com/photo-1507143550189-fed454f93097',
    'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e',
    'https://images.unsplash.com/photo-1504198453319-5ce911bafcde',
    'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99',
    'https://images.unsplash.com/photo-1516972810927-80185027ca84',
    'https://images.unsplash.com/photo-1550439062-609e1531270e',
    'https://images.unsplash.com/photo-1549692520-acc6669e2f0c'
]

t1 = time.perf_counter()


def download_image(img_url):
    img_bytes = requests.get(img_url).content
    img_name = img_url.split('/')[3]
    img_name = f'{img_name}.jpg'
    with open(img_name, 'wb') as img_file:
        img_file.write(img_bytes)
        print(f'{img_name} was downloaded...')


with concurrent.futures.ThreadPoolExecutor() as executor:
    executor.map(download_image, img_urls)


t2 = time.perf_counter()

print(f'Finished in {t2-t1} seconds')


photo-1516117172878-fd2c41f4a759.jpg was downloaded...
photo-1564135624576-c5c88640f235.jpg was downloaded...
photo-1507143550189-fed454f93097.jpg was downloaded...
photo-1530224264768-7ff8c1789d79.jpg was downloaded...
photo-1513938709626-033611b8cc03.jpg was downloaded...
photo-1532009324734-20a7a5813719.jpg was downloaded...
photo-1522364723953-452d3431c267.jpg was downloaded...
photo-1493976040374-85c8e12f0c0e.jpg was downloaded...
photo-1530122037265-a5f1f91d3b99.jpg was downloaded...
photo-1504198453319-5ce911bafcde.jpg was downloaded...
photo-1516972810927-80185027ca84.jpg was downloaded...
photo-1524429656589-6633a470097c.jpg was downloaded...
photo-1541698444083-023c97d3f4b6.jpg was downloaded...
photo-1549692520-acc6669e2f0c.jpg was downloaded...
photo-1550439062-609e1531270e.jpg was downloaded...
Finished in 2.248013639 seconds


In [2]:
import concurrent.futures
import time

start = time.perf_counter()


def do_something(seconds):
    print(f'Sleeping {seconds} second(s)...')
    time.sleep(seconds)
    return f'Done Sleeping...{seconds}'


with concurrent.futures.ProcessPoolExecutor() as executor:
    secs = [5, 4, 3, 2, 1]
    results = executor.map(do_something, secs)

    # for result in results:
    #     print(result)

finish = time.perf_counter()

print(f'Finished in {round(finish-start, 2)} second(s)')

Sleeping 5 second(s)...
Sleeping 4 second(s)...
Sleeping 3 second(s)...
Sleeping 2 second(s)...
Sleeping 1 second(s)...
Finished in 8.07 second(s)


In [3]:

import time
import concurrent.futures
from PIL import Image, ImageFilter

img_names = [
    'photo-1516117172878-fd2c41f4a759.jpg',
    'photo-1532009324734-20a7a5813719.jpg',
    'photo-1524429656589-6633a470097c.jpg',
    'photo-1530224264768-7ff8c1789d79.jpg',
    'photo-1564135624576-c5c88640f235.jpg',
    'photo-1541698444083-023c97d3f4b6.jpg',
    'photo-1522364723953-452d3431c267.jpg',
    'photo-1513938709626-033611b8cc03.jpg',
    'photo-1507143550189-fed454f93097.jpg',
    'photo-1493976040374-85c8e12f0c0e.jpg',
    'photo-1504198453319-5ce911bafcde.jpg',
    'photo-1530122037265-a5f1f91d3b99.jpg',
    'photo-1516972810927-80185027ca84.jpg',
    'photo-1550439062-609e1531270e.jpg',
    'photo-1549692520-acc6669e2f0c.jpg'
]

t1 = time.perf_counter()

size = (1200, 1200)


def process_image(img_name):
    img = Image.open(img_name)

    img = img.filter(ImageFilter.GaussianBlur(15))

    img.thumbnail(size)
    img.save(f'processed/{img_name}')
    print(f'{img_name} was processed...')


with concurrent.futures.ProcessPoolExecutor() as executor:
    executor.map(process_image, img_names)


t2 = time.perf_counter()

print(f'Finished in {t2-t1} seconds')


photo-1516117172878-fd2c41f4a759.jpg was processed...
photo-1532009324734-20a7a5813719.jpg was processed...
photo-1524429656589-6633a470097c.jpg was processed...
photo-1530224264768-7ff8c1789d79.jpg was processed...
photo-1564135624576-c5c88640f235.jpg was processed...
photo-1522364723953-452d3431c267.jpg was processed...
photo-1541698444083-023c97d3f4b6.jpg was processed...
photo-1507143550189-fed454f93097.jpg was processed...
photo-1513938709626-033611b8cc03.jpg was processed...
photo-1493976040374-85c8e12f0c0e.jpg was processed...
photo-1504198453319-5ce911bafcde.jpg was processed...
photo-1530122037265-a5f1f91d3b99.jpg was processed...
photo-1516972810927-80185027ca84.jpg was processed...
photo-1549692520-acc6669e2f0c.jpg was processed...
photo-1550439062-609e1531270e.jpg was processed...
Finished in 21.500180720999992 seconds


In [ ]:
import concurrent.futures
import time

start = time.perf_counter()


def do_something(seconds):
    print(f'Sleeping {seconds} second(s)...')
    time.sleep(seconds)
    return f'Done Sleeping...{seconds}'


with concurrent.futures.ThreadPoolExecutor() as executor:
    secs = [5, 4, 3, 2, 1]
    results = executor.map(do_something, secs)

    # for result in results:
    #     print(result)


"""
threads = []

for _ in range(10):
   t = threading.Thread(target=do_something, args=[1.5])
   t.start()
   threads.append(t)

for thread in threads:
    thread.join()

"""
finish = time.perf_counter()

print(f'Finished in {round(finish-start, 2)} second(s)')
